name: JUnit Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - DEV
          - QA
          - PROD

env:
  Greeting: Servus

jobs:
  password_please:
    runs-on: ubuntu-latest
    env:
      Dialog_Partner: Testverfahren-Profis
    steps:
      - name: Secret dialog
        run: echo $Greeting $Dialog_Partner, das Passwort f√ºr $Password_Use ist ${{ secrets.LECTURE_PASSWORD }}!
        env:
          Password_use: 'the CI/CD lecture'

  build-test:
    strategy:
      matrix:
        java: [21]
    name: Build and Test with Maven on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    needs: password_please

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build and Test with Maven
        run: mvn -B clean verify
    
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

  lint:
    name: Lint with Checkstyle
    runs-on: ubuntu-latest
    needs: password_please

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
  
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    # needs: [build-test, lint]
    needs: lint
    if: ${{ github.event.inputs.environment != '' }}
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
    - name: Deploy Application
      if: ${{ vars.DEPLOY_URL != ''}}
      run: echo Deploying to ${{ github.event.inputs.environment }} environment at $DEPLOY_URL